title: PingHome
tagline: Blog And More
author:
  name: Ping / soowin
  email: soowindance@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  成分表：技术博客，情感博客，贴图和收藏


# Theme Settings
show_excerpts: true


# Navbar Titles
header_pages:
  - questionbox.markdown
  - about.markdown


# Build settings
remote_theme: jekyll/minima
# theme: minima
plugins:
  - jekyll-feed
